In [1]:
from keras.datasets import mnist
from keras import models
from keras import layers
from keras.utils import to_categorical
import numpy as np

train_images = np.load("omok_train5.npy")
train_labels = np.load("omok_answer5.npy")

print(train_images.shape)
print(train_labels.shape)

train_labels_c = to_categorical(train_labels,num_classes=400)
print("train_labels_c",train_labels_c)

model = models.Sequential()
model.add(layers.Dense(512, activation='relu', input_shape=(400,)))
model.add(layers.Dense(512, activation='relu'))
model.add(layers.Dense(400, activation='softmax'))


model.compile(optimizer='rmsprop',
                loss='categorical_crossentropy',
                metrics=['accuracy'])


model.fit(train_images, train_labels_c, epochs=20)
model.save('alphao5.h5')

predict_result = model.predict(train_images)
print("predict_result",predict_result)
for r in predict_result:
    ai_answer = np.argmax(r)
    ii = int(ai_answer / 20)
    jj = ai_answer % 20
    print(ai_answer,ii,jj,end=",")
    print()




(24328, 400)
(24328,)
train_labels_c [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
Epoch 1/20
761/761 [==============================] - 4s 4ms/step - loss: 4.1997 - accuracy: 0.1519
Epoch 2/20
761/761 [==============================] - 3s 4ms/step - loss: 3.7944 - accuracy: 0.1939
Epoch 3/20
761/761 [==============================] - 3s 4ms/step - loss: 3.6201 - accuracy: 0.2163
Epoch 4/20
761/761 [==============================] - 3s 4ms/step - loss: 3.4465 - accuracy: 0.2386
Epoch 5/20
761/761 [==============================] - 3s 4ms/step - loss: 3.2661 - accuracy: 0.2628
Epoch 6/20
761/761 [==============================] - 3s 4ms/step - loss: 3.0902 - accuracy: 0.2892
Epoch 7/20
761/761 [==============================] - 3s 4ms/step - loss: 2.9405 - accuracy: 0.3124
Epoch 8/20
761/761 [==============================] - 3s 4ms/step - loss: 2.8044 - accuracy: 0.3327
Epoch 9

355 17 15,
372 18 12,
290 14 10,
291 14 11,
293 14 13,
314 15 14,
311 15 11,
353 17 13,
395 19 15,
372 18 12,
352 17 12,
353 17 13,
396 19 16,
372 18 12,
373 18 13,
353 17 13,
378 18 18,
335 16 15,
398 19 18,
337 16 17,
338 16 18,
318 15 18,
394 19 14,
299 14 19,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
294 14 14,
293 14 13,
272 13 12,
277 13 17,
276 13 16,
255 12 15,
235 11 15,
273 13 13,
273 13 13,
377 18 17,
377 18 17,
313 15 13,
216 10 16,
295 14 15,
253 12 13,
271 13 11,
272 13 12,
274 13 14,
272 13 12,
236 11 16,
312 15 12,
217 10 17,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
335 16 15,
354 17 14,
314 15 14,
376 18 16,
314 15 14,
293 14 13,
313 15 13,
291 14 11,
312 15 12,
332 16 12,
352 17 12,
253 12 13,
350 17 10,
252 12 12,
255 12 15,
273 13 13,
292 14 12,
231 11 11,
250 12 10,
334 16 14,
259 12 19,
278 13 18,
377 18 17,
398 19 18,

293 14 13,
253 12 13,
334 16 14,
312 15 12,
297 14 17,
277 13 17,
313 15 13,
273 13 13,
353 17 13,
372 18 12,
273 13 13,
355 17 15,
290 14 10,
291 14 11,
269 13 9,
310 15 10,
269 13 9,
271 13 11,
234 11 14,
214 10 14,
295 14 15,
294 14 14,
289 14 9,
251 12 11,
334 16 14,
251 12 11,
289 14 9,
251 12 11,
327 16 7,
358 17 18,
337 16 17,
358 17 18,
327 16 7,
252 12 12,
230 11 10,
252 12 12,
230 11 10,
252 12 12,
195 9 15,
192 9 12,
193 9 13,
287 14 7,
230 11 10,
287 14 7,
230 11 10,
287 14 7,
249 12 9,
192 9 12,
249 12 9,
192 9 12,
249 12 9,
209 10 9,
267 13 7,
287 14 7,
191 9 11,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
316 15 16,
318 15 18,
337 16 17,
314 15 14,
295 14 15,
277 13 17,
295 14 15,
274 13 14,
276 13 16,
293 14 13,
236 11 16,
296 14 16,
358 17 18,
379 18 19,
356 17 16,
357 17 17,
235 11 15,
292 14 12,
234 11 14,
255 12 15,
236 11 16,
237 11 17,
252 12 12,
214 10 14,
252 12 12,
231 11 11,
334 16 14,
231 11 11,
253 12 13,
252 12 12,
215 10 15,
272 13 12

296 14 16,
333 16 13,
313 15 13,
252 12 12,
332 16 12,
315 15 15,
232 11 12,
315 15 15,
255 12 15,
234 11 14,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
256 12 16,
257 12 17,
237 11 17,
337 16 17,
297 14 17,
256 12 16,
255 12 15,
235 11 15,
214 10 14,
318 15 18,
319 15 19,
273 13 13,
216 10 16,
356 17 16,
375 18 15,
295 14 15,
296 14 16,
292 14 12,
311 15 11,
313 15 13,
271 13 11,
293 14 13,
333 16 13,
355 17 15,
271 13 11,
354 17 14,
357 17 17,
352 17 12,
234 11 14,
332 16 12,
312 15 12,
233 11 13,
332 16 12,
233 11 13,
253 12 13,
298 14 18,
271 13 11,
298 14 18,
213 10 13,
215 10 15,
195 9 15,
298 14 18,
195 9 15,
298 14 18,
290 14 10,
213 10 13,
290 14 10,
235 11 15,
174 8 14,
153 7 13,
194 9 14,
192 9 12,
193 9 13,
192 9 12,
192 9 12,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
256 12 16,
235 11 15,
296 14 16,
235 11 15,
257 12 17,
234 11 14,
274 13 14,
276 13 16,
296 14 16,
253 12 13,
252 12 12,
294 14 14,
215 10 1

190 9 10,
150 7 10,
190 9 10,
150 7 10,
190 9 10,
150 7 10,
190 9 10,
150 7 10,
167 8 7,
207 10 7,
167 8 7,
150 7 10,
167 8 7,
207 10 7,
148 7 8,
129 6 9,
148 7 8,
129 6 9,
148 7 8,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
256 12 16,
314 15 14,
354 17 14,
257 12 17,
375 18 15,
236 11 16,
215 10 15,
375 18 15,
215 10 15,
215 10 15,
194 9 14,
299 14 19,
356 17 16,
357 17 17,
354 17 14,
252 12 12,
235 11 15,
299 14 19,
278 13 18,
273 13 13,
277 13 17,
298 14 18,
195 9 15,
298 14 18,
216 10 16,
196 9 16,
216 10 16,
177 8 17,
158 7 18,
299 14 19,
158 7 18,
271 13 11,
135 6 15,
271 13 11,
135 6 15,
271 13 11,
274 13 14,
271 13 11,
211 10 11,
271 13 11,
311 15 11,
271 13 11,
313 15 13,
288 14 8,
211 10 11,
288 14 8,
313 15 13,
288 14 8,
289 14 9,
269 13 9,
212 10 12,
307 15 7,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
313 15 13,
356 17 16,
354 17 14,
295 14 

193 9 13,
258 12 18,
178 8 18,
237 11 17,
217 10 17,
258 12 18,
238 11 18,
258 12 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
276 13 16,
256 12 16,
277 13 17,
274 13 14,
234 11 14,
314 15 14,
294 14 14,
356 17 16,
335 16 15,
292 14 12,
256 12 16,
334 16 14,
278 13 18,
279 13 19,
298 14 18,
339 16 19,
313 15 13,
332 16 12,
318 15 18,
339 16 19,
255 12 15,
353 17 13,
372 18 12,
354 17 14,
355 17 15,
374 18 14,
314 15 14,
311 15 11,
273 13 13,
290 14 10,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
355 17 15,
295 14 15,
337 16 17,
294 14 14,
332 16 12,
356 17 16,
354 17 14,
333 16 13,
276 13 16,
292 14 12,
353 17 13,
292 14 12,
291 14 11,
273 13 13,
253 12 13,
272 13 12,
250 12 10,
272 13 12,
274 13 14,
251 12 11,
371 18 11,
352 17 12,
237 11 17,
352 17 12,
371 18 11,
396 19 16,
237 11 17,
395 19 15,
237 11 17,
357 17 17,
318 15 18,
394 19 14,
299 14 19,
315 15 15,
336 16 16,
317 15 17,
2

296 14 16,
334 16 14,
335 16 15,
297 14 17,
297 14 17,
277 13 17,
256 12 16,
255 12 15,
295 14 15,
276 13 16,
274 13 14,
332 16 12,
335 16 15,
313 15 13,
351 17 11,
355 17 15,
376 18 16,
331 16 11,
377 18 17,
357 17 17,
375 18 15,
314 15 14,
258 12 18,
298 14 18,
375 18 15,
318 15 18,
374 18 14,
373 18 13,
333 16 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
295 14 15,
295 14 15,
272 13 12,
253 12 13,
355 17 15,
293 14 13,
313 15 13,
255 12 15,
236 11 16,
355 17 15,
236 11 16,
236 11 16,
217 10 17,
297 14 17,
333 16 13,
233 11 13,
213 10 13,
314 15 14,
354 17 14,
291 14 11,
396 19 16,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
295 14 15,
294 14 14,
313 15 13,
312 15 12,
354 17 14,
273 13 13,
272 13 12,
277 13 17,
276 13 16,
375 18 15,
298 14 18,
256 12 16,
298 14 18,
238 11 18,
234 11 14,
334 16 14,
215 10 15,
253 12 13,
194 9 14,
236 11 16,
214 10 14,


274 13 14,
294 14 14,
314 15 14,
294 14 14,
292 14 12,
294 14 14,
296 14 16,
358 17 18,
379 18 19,
278 13 18,
259 12 19,
313 15 13,
256 12 16,
333 16 13,
235 11 15,
353 17 13,
273 13 13,
373 18 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
335 16 15,
296 14 16,
277 13 17,
278 13 18,
235 11 15,
252 12 12,
294 14 14,
256 12 16,
255 12 15,
215 10 15,
257 12 17,
214 10 14,
258 12 18,
295 14 15,
237 11 17,
217 10 17,
236 11 16,
234 11 14,
239 11 19,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
335 16 15,
296 14 16,
277 13 17,
278 13 18,
235 11 15,
252 12 12,
255 12 15,
215 10 15,
234 11 14,
213 10 13,
234 11 14,
233 11 13,
234 11 14,
318 15 18,
237 11 17,
238 11 18,
217 10 17,
257 12 17,
314 15 14,
293 14 13,
198 9 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
335 16 15,
297 14 17,
297 14 17,
278 13 18,
235 11 15,
318 15 18,
354 17 14,
373 18 13,
375 18 15,
333 16 13,
294 14 14,
314 15 14,


278 13 18,
218 10 18,
318 15 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
256 12 16,
253 12 13,
296 14 16,
277 13 17,
276 13 16,
295 14 15,
236 11 16,
216 10 16,
334 16 14,
297 14 17,
274 13 14,
339 16 19,
338 16 18,
297 14 17,
257 12 17,
258 12 18,
314 15 14,
238 11 18,
333 16 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
277 13 17,
277 13 17,
313 15 13,
276 13 16,
274 13 14,
297 14 17,
278 13 18,
255 12 15,
318 15 18,
237 11 17,
318 15 18,
256 12 16,
235 11 15,
237 11 17,
292 14 12,
237 11 17,
218 10 18,
333 16 13,
217 10 17,
314 15 14,
238 11 18,
333 16 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
335 16 15,
255 12 15,
253 12 13,
296 14 16,
335 16 15,
334 16 14,
338 16 18,
339 16 19,
296 14 16,
356 17 16,
278 13 18,
297 14 17,
318 15 18,
298 14 18,
277 13 17,
293 14 13,
278 13 18,
234 11 14,
294 14 14,
236 11 16,
217 10 17,
236 11 16,
276 13 16,
279 13 19,

337 16 17,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
335 16 15,
255 12 15,
313 15 13,
354 17 14,
355 17 15,
375 18 15,
314 15 14,
235 11 15,
293 14 13,
276 13 16,
255 12 15,
274 13 14,
273 13 13,
253 12 13,
311 15 11,
232 11 12,
253 12 13,
294 14 14,
311 15 11,
330 16 10,
272 13 12,
251 12 11,
272 13 12,
251 12 11,
352 17 12,
252 12 12,
352 17 12,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
294 14 14,
354 17 14,
294 14 14,
295 14 15,
255 12 15,
257 12 17,
274 13 14,
276 13 16,
257 12 17,
258 12 18,
214 10 14,
234 11 14,
277 13 17,
352 17 12,
333 16 13,
350 17 10,
374 18 14,
350 17 10,
235 11 15,
193 9 13,
298 14 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
294 14 14,
354 17 14,
256 12 16,
255 12 15,
354 17 14,
333 16 13,
352 17 12,
237 11 17,
256 12 16,
257 12 17,
255 12 15,
257 12 17,


255 12 15,
233 11 13,
272 13 12,
233 11 13,
234 11 14,
233 11 13,
272 13 12,
293 14 13,
272 13 12,
293 14 13,
272 13 12,
293 14 13,
272 13 12,
231 11 11,
272 13 12,
291 14 11,
272 13 12,
291 14 11,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
335 16 15,
296 14 16,
277 13 17,
396 19 16,
334 16 14,
276 13 16,
216 10 16,
255 12 15,
257 12 17,
297 14 17,
234 11 14,
293 14 13,
253 12 13,
274 13 14,
312 15 12,
294 14 14,
314 15 14,
334 16 14,
314 15 14,
353 17 13,
372 18 12,
273 13 13,
333 16 13,
272 13 12,
196 9 16,
177 8 17,
333 16 13,
292 14 12,
311 15 11,
271 13 11,
271 13 11,
290 14 10,
355 17 15,
250 12 10,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
356 17 16,
335 16 15,
335 16 15,
295 14 15,
274 13 14,
358 17 18,
379 18 19,
314 15 14,
314 15 14,
294 14 14,
292 14 12,
294 14 14,
297 14 17,
313 15 13,
256 12 16,
255 12 15,
215 10 15,
332 16 12,
351 17 11,
273 13 13,
333 16 13,
314 15 14,
233 11 13,
214 10 14,
3

183 9 3,
24 1 4,
142 7 2,
24 1 4,
142 7 2,
24 1 4,
281 14 1,
24 1 4,
281 14 1,
24 1 4,
161 8 1,
24 1 4,
161 8 1,
24 1 4,
161 8 1,
24 1 4,
161 8 1,
24 1 4,
161 8 1,
24 1 4,
161 8 1,
24 1 4,
161 8 1,
24 1 4,
41 2 1,
24 1 4,
41 2 1,
24 1 4,
41 2 1,
24 1 4,
41 2 1,
24 1 4,
84 4 4,
24 1 4,
84 4 4,
24 1 4,
84 4 4,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
256 12 16,
235 11 15,
214 10 14,
216 10 16,
216 10 16,
216 10 16,
298 14 18,
216 10 16,
253 12 13,
258 12 18,
257 12 17,
296 14 16,
239 11 19,
296 14 16,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
355 17 15,
316 15 16,
297 14 17,
295 14 15,
274 13 14,
272 13 12,
292 14 12,
354 17 14,
275 13 15,
334 16 14,
296 14 16,
276 13 16,
192 9 12,
354 17 14,
319 15 19,
354 17 14,
356 17 16,
373 18 13,
379 18 19,
373 18 13,
374 18 14,
354 17 14,
392 19 12,
333 16 13,
291 14 11,
331 16 11,
291 14 11,
290 14 10,
291 14 11,
294 14 14,
290 14 10,
232 11 12,
269 13 9,
232 11 12,
229 11 9,


318 15 18,
252 12 12,
373 18 13,
392 19 12,
294 14 14,
290 14 10,
256 12 16,
237 11 17,
373 18 13,
392 19 12,
332 16 12,
374 18 14,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
356 17 16,
376 18 16,
375 18 15,
318 15 18,
335 16 15,
314 15 14,
257 12 17,
313 15 13,
355 17 15,
311 15 11,
339 16 19,
338 16 18,
354 17 14,
311 15 11,
235 11 15,
333 16 13,
235 11 15,
351 17 11,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
297 14 17,
297 14 17,
335 16 15,
355 17 15,
335 16 15,
314 15 14,
333 16 13,
332 16 12,
354 17 14,
297 14 17,
292 14 12,
257 12 17,
277 13 17,
252 12 12,
373 18 13,
234 11 14,
373 18 13,
392 19 12,
274 13 14,
396 19 16,
298 14 18,
234 11 14,
234 11 14,
276 13 16,
213 10 13,
318 15 18,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
277 13 17,
255 12 15,
335 16 15,
294 14 14,
354 17 14,
297 14 17,
276 13 16,
253 12 13,
236 11 16,

272 13 12,
233 11 13,
272 13 12,
233 11 13,
289 14 9,
233 11 13,
290 14 10,
308 15 8,
249 12 9,
370 18 10,
290 14 10,
288 14 8,
277 13 17,
307 15 7,
250 12 10,
337 16 17,
358 17 18,
257 12 17,
215 10 15,
276 13 16,
314 15 14,
276 13 16,
314 15 14,
276 13 16,
314 15 14,
326 16 6,
393 19 13,
326 16 6,
296 14 16,
326 16 6,
215 10 15,
212 10 12,
215 10 15,
212 10 12,
251 12 11,
190 9 10,
251 12 11,
190 9 10,
251 12 11,
175 8 15,
251 12 11,
177 8 17,
193 9 13,
195 9 15,
211 10 11,
191 9 11,
211 10 11,
169 8 9,
230 11 10,
169 8 9,
173 8 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
376 18 16,
335 16 15,
337 16 17,
354 17 14,
373 18 13,
353 17 13,
314 15 14,
353 17 13,
355 17 15,
313 15 13,
333 16 13,
295 14 15,
294 14 14,
274 13 14,
253 12 13,
337 16 17,
358 17 18,
252 12 12,
234 11 14,
252 12 12,
236 11 16,
272 13 12,
312 15 12,
311 15 11,
273 13 13,
278 13 18,
233 11 13,
235 11 15,
215 10 15,
333 16 13,
172 8 12,
212 10 12,
172 8 12,
249 12 9,


231 11 11,
250 12 10,
253 12 13,
290 14 10,
298 14 18,
299 14 19,
298 14 18,
398 19 18,
358 17 18,
379 18 19,
339 16 19,
338 16 18,
235 11 15,
215 10 15,
235 11 15,
172 8 12,
278 13 18,
172 8 12,
235 11 15,
172 8 12,
332 16 12,
172 8 12,
278 13 18,
172 8 12,
278 13 18,
329 16 9,
210 10 10,
329 16 9,
249 12 9,
172 8 12,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
335 16 15,
354 17 14,
314 15 14,
356 17 16,
271 13 11,
253 12 13,
355 17 15,
311 15 11,
333 16 13,
253 12 13,
252 12 12,
252 12 12,
352 17 12,
252 12 12,
278 13 18,
274 13 14,
234 11 14,
213 10 13,
173 8 13,
193 9 13,
233 11 13,
256 12 16,
278 13 18,
259 12 19,
209 10 9,
390 19 10,
209 10 9,
235 11 15,
277 13 17,
232 11 12,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
274 13 14,
297 14 17,
298 14 18,
356 17 16,
376 18 16,
337 16 17,
373 18 13,
355 17 15,
357 17 17,
352 17 12,
312 15 12,
3

152 7 12,
189 9 9,
131 6 11,
318 15 18,
131 6 11,
213 10 13,
131 6 11,
249 12 9,
131 6 11,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
376 18 16,
335 16 15,
337 16 17,
297 14 17,
354 17 14,
313 15 13,
235 11 15,
216 10 16,
214 10 14,
256 12 16,
237 11 17,
293 14 13,
314 15 14,
236 11 16,
257 12 17,
295 14 15,
334 16 14,
294 14 14,
296 14 16,
313 15 13,
333 16 13,
353 17 13,
333 16 13,
313 15 13,
277 13 17,
258 12 18,
217 10 17,
197 9 17,
358 17 18,
330 16 10,
331 16 11,
330 16 10,
331 16 11,
253 12 13,
232 11 12,
272 13 12,
176 8 16,
196 9 16,
177 8 17,
272 13 12,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
276 13 16,
297 14 17,
295 14 15,
335 16 15,
354 17 14,
314 15 14,
356 17 16,
271 13 11,
313 15 13,
355 17 15,
273 13 13,
292 14 12,
252 12 12,
253 12 13,
231 11 11,
294 14 14,
291 14 11,
235 11 15,
214 10 14,
237 11 17,
215 10 15,
237 11 17,
218 10 18,
216 10 16,
174 8 14,
217 10 17,
258 12 18,
2

249 12 9,
216 10 16,
249 12 9,
195 9 15,
229 11 9,
230 11 10,
249 12 9,
193 9 13,
396 19 16,
333 16 13,
393 19 13,
374 18 14,
396 19 16,
372 18 12,
393 19 13,
250 12 10,
397 19 17,
232 11 12,
393 19 13,
232 11 12,
395 19 15,
372 18 12,
395 19 15,
331 16 11,
190 9 10,
250 12 10,
190 9 10,
250 12 10,
190 9 10,
250 12 10,
250 12 10,
250 12 10,
348 17 8,
209 10 9,
348 17 8,
268 13 8,
348 17 8,
231 11 11,
265 13 5,
273 13 13,
265 13 5,
273 13 13,
247 12 7,
273 13 13,
348 17 8,
273 13 13,
348 17 8,
273 13 13,
348 17 8,
273 13 13,
151 7 11,
273 13 13,
151 7 11,
273 13 13,
151 7 11,
273 13 13,
151 7 11,
273 13 13,
151 7 11,
273 13 13,
398 19 18,
273 13 13,
398 19 18,
273 13 13,
258 12 18,
273 13 13,
258 12 18,
221 11 1,
258 12 18,
221 11 1,
185 9 5,
221 11 1,
220 11 0,
221 11 1,
220 11 0,
221 11 1,
220 11 0,
221 11 1,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
356 17 16,
235 11 15,
293 14 13,
235 11 15,
294 14 14,
235 11 15,
292 14 12,
291 14 11,
272 13 12,
33

195 9 15,
194 9 14,
195 9 15,
173 8 13,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
334 16 14,
335 16 15,
274 13 14,
295 14 15,
293 14 13,
297 14 17,
298 14 18,
236 11 16,
257 12 17,
236 11 16,
313 15 13,
355 17 15,
375 18 15,
273 13 13,
258 12 18,
256 12 16,
216 10 16,
195 9 15,
214 10 14,
298 14 18,
337 16 17,
314 15 14,
354 17 14,
314 15 14,
312 15 12,
333 16 13,
331 16 11,
332 16 12,
352 17 12,
332 16 12,
311 15 11,
314 15 14,
234 11 14,
252 12 12,
231 11 11,
232 11 12,
358 17 18,
232 11 12,
377 18 17,
232 11 12,
213 10 13,
215 10 15,
192 9 12,
232 11 12,
276 13 16,
315 15 15,
336 16 16,
317 15 17,
275 13 15,
254 12 14,
316 15 16,
296 14 16,
296 14 16,
256 12 16,
255 12 15,
235 11 15,
296 14 16,
235 11 15,
214 10 14,
314 15 14,
294 14 14,
295 14 15,
335 16 15,
354 17 14,
352 17 12,
332 16 12,
174 8 14,
215 10 15,
174 8 14,
176 8 16,
196 9 16,
215 10 15,
196 9 16,
232 11 12,
196 9 16,
353 17 13,
216 10 16,
235 11 15,
197 9 17,
232 11 12,
277 13 17,
2

295 14 15,
375 18 15,
